### PR TITLE
qtcreator 10.0.0

### PR DESCRIPTION
**Pull request by UTsweetyfish**
Relax dependency on clangd. (14 -> 13)

### CODE REVIEW

**Comment by UTsweetyfish** [comment]
develop 里面的 qt6 相关包没升级完，qt6-base是 6.4.2，但是 qt6-quicktimeline,qt6-serialport,qt6-shadertools,qt6-svg,qt6-declarative,qt6-quick3d,qt6-tools 都是 6.2.4

**Comment by UTsweetyfish** [comment]
> develop 里面的 qt6 相关包没升级完，qt6-base是 6.4.2，但是 qt6-quicktimeline,qt6-serialport,qt6-shadertools,qt6-svg,qt6-declarative,qt6-quick3d,qt6-tools 都是 6.2.4

这个已经解决了，现在退回到 6.2.4 了

**Comment by UTsweetyfish** [comment]
x86_64 failed with https://bugs.debian.org/1021117

**Comment by UTsweetyfish** [comment]
https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commit/4dbb897faa77bda7883fa72145d6281771ff6833

**Comment by UTsweetyfish** [comment]
https://github.com/deepin-community/llvm-toolchain-13/pull/1

**Review by Zeno-sole — APPROVED** [review]

**Pull request merged**
